# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from random import randint, choice

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap
from PyQt5.QtGui import QIcon
from PIL import Image
import copy


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1218, 827)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.width_spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.width_spinBox.setMinimumSize(QtCore.QSize(100, 0))
        self.width_spinBox.setObjectName("width_spinBox")
        self.gridLayout.addWidget(self.width_spinBox, 4, 5, 1, 1)
        self.height_spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.height_spinBox.setMinimumSize(QtCore.QSize(100, 0))
        self.height_spinBox.setObjectName("height_spinBox")
        self.gridLayout.addWidget(self.height_spinBox, 4, 3, 1, 1)
        self.quantity_spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.quantity_spinBox.setMinimumSize(QtCore.QSize(70, 0))
        self.quantity_spinBox.setObjectName("quantity_spinBox")
        self.gridLayout.addWidget(self.quantity_spinBox, 4, 13, 1, 1)
        self.apply_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.apply_pushButton.setMinimumSize(QtCore.QSize(70, 40))
        self.apply_pushButton.setStyleSheet("font: 12pt \"MS PGothic\";\n"
                                            "")
        self.apply_pushButton.setObjectName("apply_pushButton")
        self.gridLayout.addWidget(self.apply_pushButton, 4, 15, 1, 1)
        self.width_label = QtWidgets.QLabel(self.centralwidget)
        self.width_label.setMinimumSize(QtCore.QSize(10, 0))
        self.width_label.setMaximumSize(QtCore.QSize(200, 40))
        self.width_label.setStyleSheet("font: 12pt \"MS PGothic\";")
        self.width_label.setObjectName("width_label")
        self.gridLayout.addWidget(self.width_label, 3, 5, 1, 2)
        self.max_height_label = QtWidgets.QLabel(self.centralwidget)
        self.max_height_label.setObjectName("max_height_label")
        self.gridLayout.addWidget(self.max_height_label, 4, 4, 1, 1)
        self.max_width_label = QtWidgets.QLabel(self.centralwidget)
        self.max_width_label.setObjectName("max_width_label")
        self.gridLayout.addWidget(self.max_width_label, 4, 6, 1, 1)
        self.main_image_label = QtWidgets.QLabel(self.centralwidget)
        self.main_image_label.setMinimumSize(QtCore.QSize(1200, 700))
        self.main_image_label.setMaximumSize(QtCore.QSize(1200, 700))
        self.main_image_label.setStyleSheet("background-color: rgb(118, 255, 97);")
        self.main_image_label.setText("")
        self.main_image_label.setObjectName("main_image_label")
        self.gridLayout.addWidget(self.main_image_label, 0, 0, 3, 17)
        self.blue_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.blue_pushButton.setObjectName("blue_pushButton")
        self.gridLayout.addWidget(self.blue_pushButton, 4, 11, 1, 1)
        self.green_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.green_pushButton.setObjectName("green_pushButton")
        self.gridLayout.addWidget(self.green_pushButton, 4, 10, 1, 1)
        self.color_label = QtWidgets.QLabel(self.centralwidget)
        self.color_label.setStyleSheet("font: 12pt \"MS PGothic\";")
        self.color_label.setObjectName("color_label")
        self.gridLayout.addWidget(self.color_label, 3, 10, 1, 1)
        self.red_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.red_pushButton.setObjectName("red_pushButton")
        self.gridLayout.addWidget(self.red_pushButton, 4, 9, 1, 1)
        self.name_im_label = QtWidgets.QLabel(self.centralwidget)
        self.name_im_label.setStyleSheet("font: 12pt \"MS PGothic\";")
        self.name_im_label.setObjectName("name_im_label")
        self.gridLayout.addWidget(self.name_im_label, 3, 0, 1, 1)
        self.load_im_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.load_im_pushButton.setObjectName("load_im_pushButton")
        self.gridLayout.addWidget(self.load_im_pushButton, 4, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 4, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 4, 8, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 4, 12, 1, 1)
        self.height_label = QtWidgets.QLabel(self.centralwidget)
        self.height_label.setMinimumSize(QtCore.QSize(10, 0))
        self.height_label.setStyleSheet("font: 12pt \"MS PGothic\";")
        self.height_label.setObjectName("height_label")
        self.gridLayout.addWidget(self.height_label, 3, 3, 1, 2)
        self.image_name_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.image_name_lineEdit.setObjectName("image_name_lineEdit")
        self.gridLayout.addWidget(self.image_name_lineEdit, 4, 0, 1, 1)
        self.quantity_label = QtWidgets.QLabel(self.centralwidget)
        self.quantity_label.setStyleSheet("font: 12pt \"MS PGothic\";")
        self.quantity_label.setObjectName("quantity_label")
        self.gridLayout.addWidget(self.quantity_label, 3, 13, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1218, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.apply_pushButton.setText(_translate("MainWindow", "Apply"))
        self.width_label.setText(_translate("MainWindow", "Width of surface"))
        self.max_height_label.setText(_translate("MainWindow", "Maximum - 1000"))
        self.max_width_label.setText(_translate("MainWindow", "Maximum - 1600"))
        self.blue_pushButton.setText(_translate("MainWindow", "Blue"))
        self.green_pushButton.setText(_translate("MainWindow", "Green"))
        self.color_label.setText(_translate("MainWindow", "Color of surface"))
        self.red_pushButton.setText(_translate("MainWindow", "Red"))
        self.name_im_label.setText(_translate("MainWindow", "Name of image"))
        self.load_im_pushButton.setText(_translate("MainWindow", "Load"))
        self.height_label.setText(_translate("MainWindow", "Height of surface"))
        self.quantity_label.setText(_translate("MainWindow", "Quantity"))



if __name__ == "__main__":
    # try:
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()

    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
# except IndexError:
#     print()
