# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/versions/wertex.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(376, 524)
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 30, 331, 471))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.Name = QtWidgets.QLabel(self.layoutWidget)
        self.Name.setObjectName("Name")
        self.verticalLayout_5.addWidget(self.Name)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.FileNameLineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.FileNameLineEdit.setObjectName("FileNameLineEdit")
        self.horizontalLayout_7.addWidget(self.FileNameLineEdit)
        self.UploadButton = QtWidgets.QPushButton(self.layoutWidget)
        self.UploadButton.setObjectName("UploadButton")
        self.horizontalLayout_7.addWidget(self.UploadButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.verticalLayout.addLayout(self.verticalLayout_5)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Wid = QtWidgets.QLabel(self.layoutWidget)
        self.Wid.setObjectName("Wid")
        self.horizontalLayout_3.addWidget(self.Wid)
        self.Hei = QtWidgets.QLabel(self.layoutWidget)
        self.Hei.setObjectName("Hei")
        self.horizontalLayout_3.addWidget(self.Hei)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.Width = QtWidgets.QSpinBox(self.layoutWidget)
        self.Width.setObjectName("Width")
        self.horizontalLayout_4.addWidget(self.Width)
        self.Height = QtWidgets.QSpinBox(self.layoutWidget)
        self.Height.setObjectName("Height")
        self.horizontalLayout_4.addWidget(self.Height)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Quant = QtWidgets.QLabel(self.layoutWidget)
        self.Quant.setObjectName("Quant")
        self.horizontalLayout_2.addWidget(self.Quant)
        self.Qual = QtWidgets.QLabel(self.layoutWidget)
        self.Qual.setObjectName("Qual")
        self.horizontalLayout_2.addWidget(self.Qual)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.Quantity = QtWidgets.QSpinBox(self.layoutWidget)
        self.Quantity.setObjectName("Quantity")
        self.horizontalLayout_6.addWidget(self.Quantity)
        self.Quality = QtWidgets.QSpinBox(self.layoutWidget)
        self.Quality.setObjectName("Quality")
        self.horizontalLayout_6.addWidget(self.Quality)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Fig = QtWidgets.QLabel(self.layoutWidget)
        self.Fig.setObjectName("Fig")
        self.horizontalLayout.addWidget(self.Fig)
        self.Gen = QtWidgets.QLabel(self.layoutWidget)
        self.Gen.setObjectName("Gen")
        self.horizontalLayout.addWidget(self.Gen)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.Fightings = QtWidgets.QSpinBox(self.layoutWidget)
        self.Fightings.setObjectName("Fightings")
        self.horizontalLayout_5.addWidget(self.Fightings)
        self.Generation = QtWidgets.QSpinBox(self.layoutWidget)
        self.Generation.setObjectName("Generation")
        self.horizontalLayout_5.addWidget(self.Generation)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.StartButton = QtWidgets.QPushButton(self.layoutWidget)
        self.StartButton.setObjectName("StartButton")
        self.verticalLayout.addWidget(self.StartButton)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Name.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt;\">Имя файла</span></p></body></html>"))
        self.UploadButton.setText(_translate("Form", "Загрузить"))
        self.Wid.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt;\">Ширина</span></p></body></html>"))
        self.Hei.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt;\">Высота</span></p></body></html>"))
        self.Quant.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt;\">Количество</span></p></body></html>"))
        self.Qual.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt;\">Качество</span></p></body></html>"))
        self.Fig.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt;\">Сравнения</span></p></body></html>"))
        self.Gen.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt;\">Поколения</span></p></body></html>"))
        self.StartButton.setText(_translate("Form", "Старт"))

    def get_text(self, Form):
        pass

if __name__ == "__main__":
    # try:
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()

    ui = Ui_Form()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())